### PR TITLE
manifest error

### PR DESCRIPTION
**Pull request by tlvince**
I get the following error when packing Fidelio:

> Invalid value for 'permissions[4]'.

This solves it under Chromium v6.0.472.62 (0) Linux.

### CODE REVIEW

**Comment by nikcub** [comment]
Interesting - that is the permission request for chrome://favicon - which is a shortcut to extract the favicon for a site, which I was going to add on the options page. The documentation doesn't mention a minimum version requirement for it, but I will take it out and just link to the favicons directly. I am running Chromium 9 and 4, and it worked on both!

I have already made the update, it will be in the next release which I will push later today. Thanks for logging the issue.

**Comment by nikcub** [comment]
1.0.3 is out - issue closed, thanks!

**Comment by tlvince** [comment]
Same issue I'm afraid:

```
Invalid value for 'permissions[2]'.
```

**Comment by nikcub** [comment]
My fault - the URL was still pointing to the old version after I pushed the update. I just incremented it to 1.0.4 now with all the new updates (for real this time). Let me know how it is.

btw, I am testing on chromium 4, 9 and chrome 7

**Comment by tlvince** [comment]
Sorry, I was referring to packing the source from GitHub manually. Anyway, I've just updated to Chrome 7 and the issue seems to have solved itself. Thanks.

**Pull request closed without merging**
